fun main(args: Array<String>) {
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    */

    var fibonacci = arrayListOf<Int>(1,2)
    var fibonacciEven = arrayListOf<Int>()

    var step = 1
    var number = 0
    var limit = 4000000

    while (number in 0..limit) {
        number = fibonacci[step] + fibonacci[step-1]
        if (number < limit) {
            fibonacci.add(number)
            step++
        } else {
            break
        }
    }
    // fibonacci.filterTo(fibonacciEven) { it % 2 == 0 }  // Alternative solution to for loop
    for (number in fibonacci){
        if (number % 2 == 0) {
            fibonacciEven.add(number)
        }
    }
    println(fibonacciEven)
    println(fibonacciEven.sum())
}
